<?php

namespace app\api\controller;

use think\facade\Db;
use GatewayClient\Gateway;
use TencentCloud\Common\Credential;
use TencentCloud\Common\Profile\ClientProfile;
use TencentCloud\Common\Profile\HttpProfile;
use TencentCloud\Common\Exception\TencentCloudSDKException;
use TencentCloud\Live\V20180801\LiveClient;
use TencentCloud\Live\V20180801\Models\DescribeLiveStreamStateRequest;
use AlibabaCloud\Client\AlibabaCloud;

/**
 * ============================================================================
 * DSKMS多用户商城
 * ============================================================================
 * 版权所有 2014-2028 长沙德尚网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.csdeshang.com
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和使用 .
 * 不允许对程序代码以任何形式任何目的的再发布。
 * ============================================================================
 * 虚拟订单控制器
 */
class MemberLive extends MobileMember {

    public function initialize() {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function get_live_info() {
        $live_apply_id = input('param.live_apply_id');
        if (!$live_apply_id) {
            ds_json_encode(10001, lang('param_error'));
        }

        //获取最近未结束的直播
        $live_apply_model = model('live_apply');
        $condition = array();
        $condition[] = array('live_apply_state', '=', 1);
        $condition[] = array('live_apply_end_time', '>', TIMESTAMP);
//        $condition[] = array('live_apply_type','=',1);
        $condition[] = array('live_apply_id', '=', $live_apply_id);
        $live_apply = $live_apply_model->getLiveApplyInfo($condition);
        if (!$live_apply) {
            ds_json_encode(10001, '没有符合条件的直播');
        }
        if ($live_apply['live_apply_type'] == 1) {
            $goodscourses = model('goodscourses')->getOneGoodscourses(array('goodscourses_type'=>1,'goodscourses_type_id' => $live_apply_id));
            if (!$goodscourses) {
                ds_json_encode(10001, '课程章节不存在');
            }

            $goods = model('goods')->getGoodsOnlineInfoByID($goodscourses['goods_id']);
            if (!$goods) {
                ds_json_encode(10001, '课程不存在');
            }

            if ($goodscourses['goodscourses_free'] == 0) {
                $condition = array();
                $condition[] = array('buyer_id', '=', $this->member_info['member_id']);
                $condition[] = array('goods_id', '=', $goodscourses['goods_id']);
                $condition[] = array('order_state', 'in', array(ORDER_STATE_PAY, ORDER_STATE_SUCCESS));
                $condition[] = array('refund_state', '=', 0);
                $vrorder = model('vrorder')->getVrorderInfo($condition);
                if (!$vrorder) {
                    ds_json_encode(10001, '没有符合条件的订单');
                }
            }
        }


        //判断当前流状态
        if (config('ds_config.video_type') == 'aliyun') {
            if (!config('ds_config.aliyun_live_push_domain')) {
                ds_json_encode(10001, '未设置推流域名');
            }
            if (!config('ds_config.aliyun_live_push_key')) {
                ds_json_encode(10001, '未设置推流key');
            }
            if (!config('ds_config.aliyun_live_play_domain')) {
                ds_json_encode(10001, '未设置播流域名');
            }
            if (!config('ds_config.aliyun_live_play_key')) {
                ds_json_encode(10001, '未设置播流key');
            }
            $regionId = 'cn-shanghai';
            AlibabaCloud::accessKeyClient(config('ds_config.aliyun_access_key_id'), config('ds_config.aliyun_access_key_secret'))
                    ->regionId($regionId)
                    ->asDefaultClient();

            try {
                $result = AlibabaCloud::rpc()
                        ->product('live')
                        // ->scheme('https') // https | http
                        ->version('2016-11-01')
                        ->action('DescribeLiveStreamsOnlineList')
                        ->method('POST')
                        ->host('live.aliyuncs.com')
                        ->options([
                            'query' => [
                                'RegionId' => $regionId,
                                'DomainName' => config('ds_config.aliyun_live_push_domain'),
                                'AppName' => "live",
                                'StreamName' => 'live_apply_' . $live_apply['live_apply_id'],
                                'PageSize' => "1",
                                'PageNum' => "1",
                                'QueryType' => "strict",
                            ],
                        ])
                        ->request();
                if (!$result->TotalNum) {
                    ds_json_encode(10001, '主播不在线：' . ($live_apply['live_apply_push_message'] ? $live_apply['live_apply_push_message'] : ''));
                }
            } catch (\Exception $e) {
                ds_json_encode(10001, $e->getMessage());
            }
        } else {
            if (!config('ds_config.live_push_domain')) {
                ds_json_encode(10001, '未设置推流域名');
            }
            if (!config('ds_config.live_push_key')) {
                ds_json_encode(10001, '未设置推流key');
            }
            if (!config('ds_config.live_play_domain')) {
                ds_json_encode(10001, '未设置拉流域名');
            }
            try {

                $cred = new Credential(config('ds_config.vod_tencent_secret_id'), config('ds_config.vod_tencent_secret_key'));
                $httpProfile = new HttpProfile();
                $httpProfile->setEndpoint("live.tencentcloudapi.com");

                $clientProfile = new ClientProfile();
                $clientProfile->setHttpProfile($httpProfile);
                $client = new LiveClient($cred, "", $clientProfile);

                $req = new DescribeLiveStreamStateRequest();

                $params = '{"AppName":"live","DomainName":"' . config('ds_config.live_push_domain') . '","StreamName":"' . 'live_apply_' . $live_apply['live_apply_id'] . '"}';
                $req->fromJsonString($params);


                $resp = $client->DescribeLiveStreamState($req);
            } catch (TencentCloudSDKException $e) {
                ds_json_encode(10001, $e->getMessage());
            }
            if ($resp->StreamState != 'active') {
                ds_json_encode(10001, '主播不在线：' . ($live_apply['live_apply_push_message'] ? $live_apply['live_apply_push_message'] : ''));
            }
        }

        //生成推流url
        $live_apply['live_apply_push_url'] = model('live_apply')->getPushUrl('live_apply_' . $live_apply['live_apply_id'], $live_apply['live_apply_end_time']);
        //生成拉流url
        $live_apply['live_apply_play_url'] = model('live_apply')->getPlayUrl('live_apply_' . $live_apply['live_apply_id'], $live_apply['live_apply_end_time']);
        $live_apply['live_apply_play_rtmp_url'] = model('live_apply')->getPlayUrl('live_apply_' . $live_apply['live_apply_id'], $live_apply['live_apply_end_time'],true);

        if ($live_apply['live_apply_play_time'] > TIMESTAMP) {
            ds_json_encode(10001, '未到直播时间');
        }
        $extral_info = array('live_apply_name' => $live_apply['live_apply_id'] . '号直播间', 'live_apply_image' => goods_cthumb(''));
        if ($live_apply['live_apply_type_id']) {
            switch ($live_apply['live_apply_type']) {
                case LIVE_APPLY_TYPE_COURSE:
                    $extral_info['live_apply_name'] = $goods['goods_name'] . '：' . $goodscourses['goodscourses_name'];
                    $extral_info['live_apply_image'] = goods_cthumb($goods['goods_image']);
                    break;
            }
        }
        $online_info = false;
        if (config('ds_config.instant_message_register_url')) {
            require_once ROOT_PATH . '/GatewayWorker/vendor/workerman/gatewayclient/Gateway.php';
            // 设置GatewayWorker服务的Register服务ip和端口，请根据实际情况改成实际值(ip不能是0.0.0.0)
            try {
                Gateway::$registerAddress = config('ds_config.instant_message_register_url');
                $online_info = array(
                    'online_count' => Gateway::getClientIdCountByGroup('live_apply_' . $live_apply_id),
                    'online_list' => Gateway::getClientSessionsByGroup('live_apply_' . $live_apply_id),
                );
            } catch (\Exception $e) {
                $msg = $e->getMessage();
            }
        }
        ds_json_encode(10000, '', array('live_apply_info' => array_merge($live_apply, $extral_info, array('instant_message_url' => config('ds_config.instant_message_gateway_url'))), 'online_info' => $online_info));
    }

    function join_live() {
        $live_apply_id = input('param.live_apply_id');
        $client_id = input('param.client_id');
        if (!config('ds_config.instant_message_register_url')) {
            ds_json_encode(10001, '未设置直播聊天gateway地址');
        }
        $live_apply_model = model('live_apply');
        $condition = array();
        $condition[] = array('live_apply_state', '=', 1);
        $condition[] = array('live_apply_id', '=', $live_apply_id);

        $live_apply = $live_apply_model->getLiveApplyInfo($condition);
        if (empty($live_apply)) {
            ds_json_encode(10001, '直播不存在');
        }
        if ($live_apply['live_apply_type'] == 1) {
            $goodscourses = model('goodscourses')->getOneGoodscourses(array('live_apply_id' => $live_apply_id));
            if (!$goodscourses) {
                ds_json_encode(10001, '课程章节不存在');
            }
            $goods = model('goods')->getGoodsOnlineInfoByID($goodscourses['goods_id']);
            if (!$goods) {
                ds_json_encode(10001, '课程不存在');
            }
            if ($goodscourses['goodscourses_free'] == 0) {
                $condition = array();
                $condition[] = array('buyer_id', '=', $this->member_info['member_id']);
                $condition[] = array('goods_id', '=', $goodscourses['goods_id']);
                $condition[] = array('order_state', 'in', array(ORDER_STATE_PAY, ORDER_STATE_SUCCESS));
                $condition[] = array('refund_state', '=', 0);
                $vrorder = model('vrorder')->getVrorderInfo($condition);
                if (!$vrorder) {
                    ds_json_encode(10001, '未订阅此直播');
                }
            }
        }


        require_once ROOT_PATH . '/GatewayWorker/vendor/workerman/gatewayclient/Gateway.php';
        // 设置GatewayWorker服务的Register服务ip和端口，请根据实际情况改成实际值(ip不能是0.0.0.0)
        try {
            Gateway::$registerAddress = config('ds_config.instant_message_register_url');
            // client_id与uid绑定
            Gateway::bindUid($client_id, '0:' . $this->member_info['member_id']);
            $online_item = array(
                'instant_message_from_avatar' => get_member_avatar_for_id($this->member_info['member_id']),
                'instant_message_from_id' => $this->member_info['member_id'],
                'instant_message_from_type' => 0,
                'instant_message_from_name' => $this->member_info['member_name']
            );
            Gateway::setSession($client_id, $online_item);
            // 加入某个群组（可调用多次加入多个群组）
            Gateway::joinGroup($client_id, 'live_apply_' . $live_apply_id);
            //更新在线人数
            Gateway::sendToGroup('live_apply_' . $live_apply_id, json_encode(array(
                'type' => 'join',
                'online_count' => Gateway::getClientIdCountByGroup('live_apply_' . $live_apply_id),
                'online_list' => Gateway::getClientSessionsByGroup('live_apply_' . $live_apply_id)
            )));
        } catch (\Exception $e) {
            ds_json_encode(10001, $e->getMessage());
        }
        ds_json_encode(10000, '');
    }

    function leave_live() {
        $live_apply_id = input('param.live_apply_id');
        $client_id = input('param.client_id');
        if (!config('ds_config.instant_message_register_url')) {
            ds_json_encode(10001, '未设置直播聊天gateway地址');
        }
        try {
            require_once ROOT_PATH . '/GatewayWorker/vendor/workerman/gatewayclient/Gateway.php';
            // 设置GatewayWorker服务的Register服务ip和端口，请根据实际情况改成实际值(ip不能是0.0.0.0)
            Gateway::$registerAddress = config('ds_config.instant_message_register_url');
            // client_id与uid绑定
            Gateway::unbindUid($client_id, '0:' . $this->member_info['member_id']);
            // 加入某个群组（可调用多次加入多个群组）
            Gateway::leaveGroup($client_id, 'live_apply_' . $live_apply_id);
            //更新在线人数
            Gateway::sendToGroup('live_apply_' . $live_apply_id, json_encode(array(
                'type' => 'leave',
                'online_count' => Gateway::getClientIdCountByGroup('live_apply_' . $live_apply_id),
                'online_list' => Gateway::getClientSessionsByGroup('live_apply_' . $live_apply_id),
            )));
        } catch (\Exception $e) {
            ds_json_encode(10001, $e->getMessage());
        }
        ds_json_encode(10000, '');
    }

}
